### ISSUE TITLE
IMIS package has been remove from CRAN

### ISSUE THREAD

**Issue by gloriamacia** [DARTH-git/darthpack#7]
`source("analysis/03_calibration.R", echo = TRUE)`

will return `Error in loadNamespace(x) : there is no package called ‘IMIS’` because IMIS was removed from Cran and no longer runs in the latest versions of R

https://cran.r-project.org/web/packages/IMIS/index.html

The workaround is to comment out this line i.e. do not run calibration, but ideally, the framework example should be updated with another equivalent package to remain and end-to-end working example.

**Comment by feralaes** [comment]
Dear Gloria, thank you for bringing this to our attention. I added code to download the archived version of IMIS in this line: https://github.com/DARTH-git/darthpack/blob/8f82230ab0ee6261ee569f0ef97d0ed341dcaeb5/analysis/03_calibration.R#L22

You should be able to install IMIS now and run the working example from beginning to end :).

**Comment by gloriamacia** [comment]
amazing! such an speedy reply

**Comment by feralaes** [comment]
Thank you for raising this issue!

From: Gloria Macia ***@***.***>
Date: Wednesday, January 17, 2024 at 1:26 PM
To: DARTH-git/darthpack ***@***.***>
Cc: Fernando Alarid Escudero ***@***.***>, Comment ***@***.***>
Subject: Re: [DARTH-git/darthpack] IMIS package has been remove from CRAN (Issue #7)

amazing! such an speedy reply
